MainProject/apps/ContactUs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('contact-us/', views.contact, name='contact'),
    path('contact-us/success', views.contact_success, name='success')

]

MainProject/apps/SubjectTags/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('posts/tag/<slug:tag_slug>/', views.post_list_by_tag, name='post_list_by_tag'),
    path('blogs/tag/<slug:tag_slug>/', views.blogs_list_by_tag, name='blogs_list_by_tag'),
]

MainProject/apps/URLsub/urls.py
#URLsub/urls.py
from django.urls import path
from . import views
from .views import URLsubDetailView, add_additional_description

app_name = 'URLsub'  # Add the app namespace


urlpatterns = [
    path('urlsub/', views.urlsub, name='urlsub'),
    path('urlsub/thanks_url', views.url_thanks, name='thanks_url'),
    path('urlsub/<int:pk>/<slug:slug>/', URLsubDetailView.as_view(), name='urlsub_detail'),
    path('urlsub/<int:pk>/<slug:slug>/add_additional_description/', add_additional_description, name='add_additional_description'),

]

MainProject/apps/core/urls.py
# core/urls.py
from django.urls import path
from . import views
from .views import  HomeView, PostView, PostCreateView, PostUpdateView, PostDeleteView,  ForumView, URLSpecificPostCreateView, URLSpecificPostView, URLSpecificForumView, YourPostsView, SavedForLaterView, LikedView
#, AddDislike, AddLike, 

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('Forum', ForumView.as_view(), name='forum'),
    path('post/<int:pk>/<slug:slug>/', PostView.as_view(), name='post'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),

    path('post/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),

    path('About/', views.AboutView, name='about'),
    path('Trending/', views.TrendingView, name='trending'),
    path('Recommendations/', views.RecommendationsView, name='recommendations'),
    path('Subscriptions/', views.SubscriptionsView, name='subscriptions'),

    path('YourPosts/', views.YourPostsView, name='yourposts'),

    path('SavedForLater/', views.SavedForLaterView, name='savedforlater'),
    path('Liked/', views.LikedView, name='liked'),

    path('urlsub/<int:pk>/<slug:slug>/create_post', URLSpecificPostCreateView.as_view(), name='urlsub_post_create'),
    path('urlsub/<int:pk>/<slug:slug>/<int:post_pk>/<slug:post_slug>/', URLSpecificPostView.as_view(), name='url_specific_post'),
    path('urlsub/<int:pk>/<slug:slug>/discussion/', URLSpecificForumView.as_view(), name='url_specific_forum'),

 #   path('rsstest/', RSSPageView.as_view(), name="rsstest"),

]

MainProject/apps/users/urls.py
# users/urls.py        
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView
)

from .views import signup, log_in, log_out, profile, edit_profile
from django.urls import reverse_lazy
from . import views


urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    

    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        success_url='/users/password_reset/done/'),
        name='password_reset'
    ),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url='/users/reset/done/'),
        name='password_reset_confirm'
    ),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),

    path('profile/<str:username>/', profile, name='profile'),

    path('edit-profile/<str:username>/', edit_profile, name='edit_profile'),  # Include 'username' parameter

    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done')),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),



]

MainProject/blog/urls.py
# blog/urls.py

"""blog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve





urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('apps.core.urls', 'core'), namespace='core')),    
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),  
    path('', include(('apps.ContactUs.urls', 'ContactUs'), namespace='ContactUs')),
    path('', include(('apps.URLsub.urls', 'URLsub'), namespace='URLsub')),  
    path('', include(('apps.Search.urls', 'Search'), namespace='Search')),
    path('', include(('SubjectTags.urls', 'SubjectTags'), namespace='SubjectTags')),
    path('', include(('StripePayment.urls', 'StripePayment'), namespace='StripePayment')),
    path('legal/', include('apps.legal.urls')),  # Include legal app URLs




]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
]

MainProject/apps/core/models.py
# Create your models here.
# core/models.py
from django.db import models
from django.conf import settings
from taggit.managers import TaggableManager
from apps.users.models import User
from apps.URLsub.models import URLsub

#class Tag(models.Model):
    # Remove the 'name' field, as django-taggit handles tags internally
#    tags = TaggableManager()

 #   class Meta:
  #      app_label = 'core'

   # def __str__(self):
    #    return ', '.join(self.tags.names())  # Return a comma-separated list of tag names




class Post(models.Model):
    title = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    content = models.TextField()
    image = models.ImageField(upload_to='Post_image/', blank=True, null=True)
    tags = TaggableManager(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now= True)
    urlsub = models.ForeignKey(URLsub, on_delete=models.CASCADE, related_name='related_posts', blank=True, null=True)


    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('core:post', args=[str(self.id), self.slug])
    
    def author_username(self):
        return self.author.username

    def author_email(self):
        return self.author.email
    

class Comment(models.Model):
    #name = models.CharField(max_length=50)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    email = models.EmailField(max_length=100)
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
       ordering = ('-created',)

    def __str__(self):
       return 'Comment by {}'.format(self.author.username)
    
    def author_username(self):
        return self.author.username

    def author_email(self):
        return self.author.email
    

#This model stores full blog recommendations
##This will come from data that has been scraped but for now it will be from 
class BlogFullRecommend(models.Model):
    title = models.CharField(max_length=200, db_index=True)
    url = models.URLField(db_index=True)
    author = models.CharField(max_length=200, db_index=True, blank=True)
    content = models.TextField(max_length=500, blank=True)
    image = models.ImageField(upload_to='BlogFullRecommend_image/', blank=True, null=True)
    tags = TaggableManager(blank=True)
    last_updated = models.DateTimeField(blank=True)

    class Meta:
        ordering = ['-last_updated']

    def __str__(self):
        return self.title
    

MainProject/apps/core/forms.py
# core/forms.py
from django import forms
from .models import Comment, Post
from taggit.forms import TagField

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('email', 'content')  # Exclude 'author' field from the form
        exclude = ['author']  # Alternatively, you can use exclude as a list

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['content'].required = True



class SubmitURL(forms.Form):
    url = forms.URLField(label='URL', max_length=200)


#class ContactUsForm(forms.ModelForm):
 #   class Meta:
  #      model = Contact
   #     fields =('name', 'email', 'content')


class PostForumForm(forms.ModelForm):
    tags = TagField()
    class Meta:
        model = Post
        fields = ["title", "content", "image", "tags"]



class URLSpecificPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "image", "tags"]

MainProject/templates/core/about.html
<!-- templates/core/post.html -->
{% extends 'base.html' %}

{% block css %}
{% load static %}  
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />


    <!-- jQuery library -->
    <script src="{% static "blog/js/jquery-3.4.1.min.js " %}"></script>

    <!-- Latest compiled JavaScript -->
    <script src="{% static "blog/js/bootstrap.min.js " %}"></script>

{% endblock css%}

{% block head_title %}{{ post.title }}{% endblock %}

{% block content %}

<!DOCTYPE html>
<html>

<main>
   
<section>
    <div class="about-content">
        
    <h1>About the WilderNet</h1>
   
    <p>
        Welcome to the WilderNet! The WilderNet is an experimental 
        project that aims to make it easier to find independent 
        blogs from amateur content creators. </p>



        <p>The WilderNet is for people who are looking for an internet experience that is fun and serendipitious.
        
        Think of it like an old-fashioned card catalog. </p>

        <p>
            This is a user-curated community. 
            We encourage users to recommend blogs they find interesting and tag your recommendations by subject. 
        </p>
    

 
    <p>Are you the owner of a blog? Add it to our catalog! 
        We do not copy your content or present it as our own.  </p>

    <br>
    <p>Help us grow our community. Sign up <a href="{% url 'users:signup' %}"> here </a>
    <p>Recommend a blog  <a href="{% url 'URLsub:urlsub' %}"  >here</a>
    <br>
    <p>Leave us a  <a href="{% url 'ContactUs:contact' %}" >question, comment or suggestion</a>
    

</section>

</div>
</main>
</body>
</html>
{% endblock content %}

MainProject/templates/core/discussion.html
<!-- templates/core/discussion.html -->
<!--This is for the url specific discussion forum-->
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The WilderNet Home</title>
    {% load static %}
    {% block css %}{% endblock css %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

  <link rel="stylesheet" type="text/css" href="{% static 'css/core/discussion.css' %}">
</head>

<div class="container mt-4">
    <!-- Button for creating a new post -->
    <a href="{% url 'core:urlsub_post_create' pk=urlsub_pk slug=urlsub_slug %}" class="btn btn-primary mb-4">
      Create New Post
  </a>

    <div class="urlsub-details">
        <h1><a href="{{ urlsub_url }}" target="_blank" class="urlsub-title">{{ urlsub_title }}</a></h1>
    </div>
    <div class="row">
    {% for post in object_list %}
    <a href="{% url 'core:url_specific_post' pk=post.urlsub.pk slug=post.urlsub.slug post_pk=post.pk post_slug=post.slug %}">
      <div class="entry">
        <div class="thumbnail">
          {% if post.image %}
          <img src="{{ post.image.url }}" alt="{{ post.title }}">
          {% else %}
          <img src="/static/img/default.png">
          {% endif %}
        </div>
        <div class="card-title">{{ post.title|truncatechars:100 }}</div>
        <div class="author">{{ post.author.username }}</div>
        <div class="card-text">{{ post.content|truncatechars:100 }}</div>
      </div>
    </a>
    {% endfor %}
  </div>
  <!-- Pagination Controls -->
{% if is_paginated %}
<ul class="pagination">
  {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
  {% else %}
    <li class="disabled"><span>&laquo;</span></li>
  {% endif %}
  {% for i in paginator.page_range %}
    {% if page_obj.number == i %}
      <li class="current"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
      <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
  {% else %}
    <li class="disabled"><span>&raquo;</span></li>
  {% endif %}
</ul>
{% endif %}
</div>
</div>

{% endblock content %}

MainProject/templates/core/home.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The WilderNet Home</title>
    {% load static %}
    {% block css %}{% endblock css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/core/home.css' %}">
</head>

<div class="container mt-4">
    <div class="row">
        {% for blog in blogs %}
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card p-3">
                <a href="{{ blog.url }}" class="blog-title d-block overflow-hidden text-truncate">{{ blog.title }}</a>
                <p class="blog-description card-text overflow-hidden text-truncate">{{ blog.description }}</p>

                <!-- Button container with spacing below -->
                <div class="button-container homepage-buttons">
                    <a href="{% url 'URLsub:urlsub_detail' blog.id blog.slug %}">
                        <div class="button-wrapper">
                            <button class="styled-button"> Details</button>
                        </div>
                    </a>
                  
                        <div class="button-wrapper">
                          <a href="{% url 'core:url_specific_forum' pk=blog.pk slug=blog.slug %}">
                            <button class="styled-button"> Discussion</button>
                        </div>
                    </a>
                </div>
                <!-- Tags section moved below the buttons -->
                <div class="tags">
                    <span class="tags-label"></span>
                    <div class="badge-container">
                        {% for tag in blog.tags.all %}
                            {% if forloop.counter <= 6 %} {# Display up to 6 tags (2 lines) #}
                                <a href="{% url 'SubjectTags:blogs_list_by_tag' tag.slug %}" class="badge badge-dark">{{ tag }}</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- Pagination Controls -->
<!-- Pagination Controls -->
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="current"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</div>
{% endblock content %}

MainProject/templates/core/post.html
<!-- templates/core/post.html -->
{% extends 'base.html' %}

{% block css %}
{% load static %}  
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />




{% endblock css%}

{% block head_title %}{{ post.title }}{% endblock %}

{% block content %}




<div class="container-fluid my-5">


      <div class="card">
        <h2 class="card-title text-center my-3">{{ post.title }}</h2>
        <div class="card-text mt-5 p-4">
          {{ post.content }}
        </div>

        <div class="text-muted text-center mb-3">
          <div>
            created: {{ post.created_on|date:"N j Y" }},
            last updated: {{ post.updated_on|timesince }},
            by 
            <a class="badge badge-secondary" href="{% url 'users:profile' post.author.username %}">
              {{ post.author.username }}
            </a>
            <a class="badge badge-secondary" href="#">{{ post.author.username }}</a>
          </div>
          <div>
            {% for tag in post.tags.all %}
            <span class="badge badge-dark">{{ tag }}</span>
   
          </div>
        </div>
        {% if post.image %}
        <img class="card-img-top" src="{{ post.image.url }}" alt="{{ post.title }}">
        {% endif %}


     
       
           

            

         
        </div>
            <a class="btn btn-primary" href="{% url 'core:post_update' post.id %}">Edit</a>
            <a class="btn btn-danger" href="{% url 'core:post_delete' post.id %}">Delete</a>
          </div>
        </div>
         
        
        
        </div>
      </div>

{% endfor %}
</div>
<hr><hr>
 <!-- List of comments -->
 {% if comments %}
 <div class="row mt-5">
   <div class="col-lg-6 offset-lg-3">
     Comment{{ comments.count|pluralize }}
     <span class="badge badge-dark ml-2">{{ comments.count }}</span>
   </div>
   {% for comment in comments %}
   <div class="col-lg-6 offset-lg-3 mt-2">
     <div class="card p-2">
       <div class="row">
         <div class="col-12">
           <img class="rounded-circle mr-2" src="{% static 'img/cat.png' %}" width="60" height="60" alt="Avatar">
           <strong>{{ comment.name }}</strong> said
         </div>
         <div class="col-12">
           <p class="m-1 mt-3">{{ comment.content }}</p>
           <p class="text-right text-muted"><small>{{ comment.created }}</small></p>
         </div>
       </div>
     </div>
   </div>
   {% endfor %}
 </div>
 {% endif %}
 

<hr>


 <!-- Form to leave comment -->
 <div class="row mt-5">
   <div class="col-lg-6 offset-lg-3">
     <h3>Leave a comment</h3>
     <form method='POST'>
       {% csrf_token %}
       <div class="form-group">
         <span class="ml-2"></span>{{ form.name.label_tag }}
         <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}" id="id_name"
           name="name" value="{{ form.name.value|default:'' }}">
       </div>
       <div class="form-group">
         <span class="ml-2"></span>
         {{ form.email.label_tag }}
         <span class="text-muted"><small>(Your email address will not be published)</small></span>
         <input type="text" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
           name="email" value="{{ form.email.value|default:'' }}">
       </div>
       <div class="form-group">
         <span class="ml-2"></span>{{ form.content.label_tag }}
         <textarea class="form-control {% if form.content.errors %}is-invalid{% endif %}" id="id_content"
           name="content" rows="4">{{ form.content.value|default:'' }}</textarea>
       </div>
       <button class="btn btn-primary ml-2" type="submit">Reply</button>
     </form>

    </div>
  </div>
</div>
{% endblock content %}



<script>
  $(document).ready(function () {
      $(".likebtn").click(function (event) {
          event.preventDefault()
          var ansid = $(this).attr('id');
          console.log(ansid)
          $.ajax({
              url: $(this).data('url'),
              type: 'POST',
              data: {
                  'post_id': ansid
                  'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                  'action': 'post'
              },
              success: function (response) {
                  $('#like_count' + ansid).text(response['total_likes']);
                  console.log(response)
                  if (response['flag']) {
                      $('#' + ansid).addClass('text-primary');
                  } else {
                      $('#' + ansid).removeClass('text-primary');
                  }
              },
              error: function (rs, e) {
                  console.log(rs.response)
              }
          });
      });
  });
</script>

MainProject/templates/core/post_form.html
<!-- templates/core/post_form.html -->
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block head_title %}{% if update %}Update post{% else %}Create a post{% endif %}{% endblock head_title %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'plugins/input-tags/tagsinput.css' %}" >



<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h2 class=" my-5">{% if update %}Update post{% else %}Create a post{% endif %}</h2>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
          {{ form.title.label_tag }}
          <input type="text" class="form-control {% if form.title.errors %}is-invalid{% endif %}" id="id_title"
            name="title" value='{{ form.title.value|default:"" }}'>
          {% if form.title.errors %}
          <div class="invalid-feedback">{{ form.title.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.content.label_tag }}
          <textarea type="text" class="form-control {% if form.content.errors %}is-invalid{% endif %}" id="id_content"
            name="content" cols="40" rows="10">{{ form.content.value|default:"" }}</textarea>
          {% if form.content.errors %}
          <div class="invalid-feedback">{{ form.content.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.image.label_tag }}<br>
          <input type="file" class="{% if form.image.errors %}is-invalid{% endif %}" id="id_image" name="image"
            accept="image/*">
          {% if form.image.errors %}
          <div class="invalid-feedback">{{ form.image.errors }}</div>
          {% endif %}
        </div>


          <div class="form-group-plugin">
            <label for="tags-input">Subject tags:
              <br>Separate tags by a comma
            </label>
        {% render_field form.tags class="form-control" id="input-tags" data-role="tagsinput" %}
          </div>


        <button type="submit" class="btn btn-primary">
        {% if update %}Update the post{% else %}Create Post{% endif %}
        </button>
      </form>

    </div>
  </div>
</div>
{% endblock content %}

MainProject/templates/core/url_specific_post.html
{% extends 'base.html' %}

{% block css %}
{% load static %}  
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
{% endblock css%}

{% block head_title %}{{ url_specific_post.title }}{% endblock %}

{% block content %} 
  <!-- Display URLsub details -->

<div class="container-fluid my-5">
    <div class="urlsub-details">
        <h3>Associated URLsub</h3>
        <p><strong>Title:</strong> {{ urlsub.title }}</p>
        <p><strong>Description:</strong> {{ urlsub.description }}</p>
        <!-- Add any other URLsub details you want to display -->
      </div>
  <div class="post-card">
    <h2 class="card-title text-center my-3">{{ url_specific_post.title }}</h2>
    <div class="card-content">
      {% if url_specific_post.image %}
      <div class="image-container">
        <img class="card-img" src="{{ url_specific_post.image.url }}" alt="{{ url_specific_post.title }}">
      </div>
      {% endif %}
      <div class="card-text">
        {{ url_specific_post.content }}
      </div>
    </div>

    <div class="text-muted text-center mb-3">
      <div>
        created: {{ url_specific_post.created_on|date:"N j Y" }},
        last updated: {{ url_specific_post.updated_on|timesince }},
        by 
        <a class="badge badge-secondary" href="{% url 'users:profile' url_specific_post.author.username %}">
          {{ url_specific_post.author.username }}
        </a>
      </div>
      <div>
        {% for tag in url_specific_post.tags.all %}
          <a href="{% url 'SubjectTags:post_list_by_tag' tag.slug %}" class="badge badge-dark">{{ tag }}</a>
        {% endfor %}
      </div>
    </div>
  </div>

  <hr>

  <!-- Form to leave comment -->
  <div class="row mt-5">
    <div class="col-lg-6 offset-lg-3">
      <h3>Leave a comment</h3>
      {% if user.is_authenticated %}
      <form method='POST'>
        {% csrf_token %}
        <input type="hidden" name="author" value="{{ user.id }}">
        <input type="hidden" name="username" value="{{ user.username }}">
        <div style="display: none;">
          <input type="email" name="email" value="{{ user.email }}">
        </div>
        {{ form.author.errors }}
        {{ form.username.errors }}
        <div class="form-group">
          {% if user.profile.avatar %}
          <img class="rounded-circle mr-2" src="{{ user.profile.avatar.url }}" width="60" height="60" alt="Avatar">
          {% else %}
          <img class="rounded-circle mr-2" src="{% static 'img/cat.png' %}" width="60" height="60" alt="Default Avatar">
          {% endif %}        
          <span class="ml-2"></span>
          {{ form.content.label_tag }}
          <textarea class="form-control {% if form.content.errors %}is-invalid{% endif %}" id="id_content"
            name="content" rows="4">{{ form.content.value|default:'' }}</textarea>
        </div>
        <button class="btn btn-primary ml-2" type="submit">Reply</button>
      </form>
      {% else %}
      <div class="navbar-nav ml-auto">
        <a href="{% url 'users:signup' %}"
          class="nav-item nav-link {% if request.path == '/users/signup/' %}active{% endif %}">Sign up</a>
        <a href="{% url 'users:login' %}">Log In</a>
      </div>
      {% endif %}
    </div>
  </div>




  <!-- List of comments -->
  {% if comments %}
  <div class="row mt-5">
    <div class="col-lg-6 offset-lg-3">
      Comment{{ comments.count|pluralize }}
      <span class="badge badge-dark ml-2">{{ comments.count }}</span>
    </div>
    {% for comment in comments %}
    <div class="col-lg-6 offset-lg-3 mt-2">
      <div class="row">
        <div class="col-12">
          {% if comment.author.profile.avatar %}
          <img class="rounded-circle mr-2" src="{{ comment.author.profile.avatar.url }}" width="60" height="60" alt="Avatar">
          {% else %}
          <img class="rounded-circle mr-2" src="{% static 'img/cat.png' %}" width="60" height="60" alt="Default Avatar">
          {% endif %}
          <strong>{{ comment.author.username }}</strong> said
        </div>
        <div class="col-12">
          <p class="m-1 mt-3">{{ comment.content }}</p>
          <p class="text-right text-muted"><small>{{ comment.created }}</small></p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}
</div>
{% endblock content %}