MainProject/apps/SubjectTags/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('posts/tag/<slug:tag_slug>/', views.post_list_by_tag, name='post_list_by_tag'),
    path('blogs/tag/<slug:tag_slug>/', views.blogs_list_by_tag, name='blogs_list_by_tag'),
]

MainProject/apps/URLsub/urls.py
#URLsub/urls.py
from django.urls import path
from . import views
from .views import URLsubDetailView, add_additional_description

app_name = 'URLsub'  # Add the app namespace


urlpatterns = [
    path('urlsub/', views.urlsub, name='urlsub'),
    path('urlsub/thanks_url', views.url_thanks, name='thanks_url'),
    path('urlsub/<int:pk>/<slug:slug>/', URLsubDetailView.as_view(), name='urlsub_detail'),
    path('urlsub/<int:pk>/<slug:slug>/add_additional_description/', add_additional_description, name='add_additional_description'),

]

MainProject/apps/core/urls.py
# core/urls.py
from django.urls import path
from . import views
from .views import  HomeView, PostView, PostCreateView, PostUpdateView, PostDeleteView,  ForumView, URLSpecificPostCreateView, URLSpecificPostView, URLSpecificForumView, YourPostsView, SavedForLaterView, LikedView
#, AddDislike, AddLike, 

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('Forum', ForumView.as_view(), name='forum'),
    path('post/<int:pk>/<slug:slug>/', PostView.as_view(), name='post'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),

    path('post/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),

    path('About/', views.AboutView, name='about'),
    path('Trending/', views.TrendingView, name='trending'),
    path('Recommendations/', views.RecommendationsView, name='recommendations'),
    path('Subscriptions/', views.SubscriptionsView, name='subscriptions'),

    path('YourPosts/', views.YourPostsView, name='yourposts'),

    path('SavedForLater/', views.SavedForLaterView, name='savedforlater'),
    path('Liked/', views.LikedView, name='liked'),

    path('urlsub/<int:pk>/<slug:slug>/create_post', URLSpecificPostCreateView.as_view(), name='urlsub_post_create'),
    path('urlsub/<int:pk>/<slug:slug>/<int:post_pk>/<slug:post_slug>/', URLSpecificPostView.as_view(), name='url_specific_post'),
    path('urlsub/<int:pk>/<slug:slug>/discussion/', URLSpecificForumView.as_view(), name='url_specific_forum'),

 #   path('rsstest/', RSSPageView.as_view(), name="rsstest"),

]

MainProject/apps/users/urls.py
# users/urls.py        
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView
)

from .views import signup, log_in, log_out, profile, edit_profile
from django.urls import reverse_lazy
from . import views


urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    

    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        success_url='/users/password_reset/done/'),
        name='password_reset'
    ),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url='/users/reset/done/'),
        name='password_reset_confirm'
    ),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),

    path('profile/<str:username>/', profile, name='profile'),

    path('edit-profile/<str:username>/', edit_profile, name='edit_profile'),  # Include 'username' parameter

    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done')),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),



]

MainProject/blog/urls.py
# blog/urls.py

"""blog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve





urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('apps.core.urls', 'core'), namespace='core')),    
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),  
    path('', include(('apps.ContactUs.urls', 'ContactUs'), namespace='ContactUs')),
    path('', include(('apps.URLsub.urls', 'URLsub'), namespace='URLsub')),  
    path('', include(('apps.Search.urls', 'Search'), namespace='Search')),
    path('', include(('SubjectTags.urls', 'SubjectTags'), namespace='SubjectTags')),
    path('', include(('StripePayment.urls', 'StripePayment'), namespace='StripePayment')),
    path('legal/', include('apps.legal.urls')),  # Include legal app URLs




]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
]

MainProject/apps/URLsub/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.conf import settings
from django.utils.text import slugify
from django.utils import timezone


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)
    tags = TaggableManager()

    def __str__(self):
        return self.name


class URLsub(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    url = models.URLField()
    title = models.TextField()
    description = models.TextField()
    tags = TaggableManager()  # Specify the through parameter
    timestamp = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, max_length=200, default='default-slug-value')  # Add the SlugField

    class Meta:
        unique_together = ('url', 'user')  # Add this unique constraint

    def author_username(self):
        return self.user.username  # Access the username of the user

    def author_email(self):
        return self.user.email 
    
    def save(self, *args, **kwargs):
        # Generate a slug before saving
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Description(models.Model):
    urlsub = models.ForeignKey(URLsub, on_delete=models.CASCADE, related_name='additional_descriptions')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  # Add the user field
    description = models.TextField()
    tags = TaggableManager()
    timestamp = models.DateTimeField(default=timezone.now)  # Add the timestamp field


    class Meta:
        ordering = ['-timestamp']  # Sort by URLsub's timestamp in descending order

MainProject/apps/URLsub/forms.py
#URLsub/forms.py
from django import forms
from .models import  URLsub, Description
from taggit.forms import TagField

class URLSubForm(forms.ModelForm):
    tags = TagField()
    class Meta:
        model = URLsub
        fields = ('url', 'title','description', 'tags')  # Include all relevant fields

    # Define custom labels
    labels = {
        'description': 'Blog Description',
        'title': 'Blog Title',
        'tags': 'Subject Tags',
        'url': 'Blog URL',
    }

class AdditionalDescriptionForm(forms.ModelForm):
    tags = TagField()

    class Meta:
        model = Description
        fields = ('description', 'tags')  # Exclude 'url' field

    # Define custom labels
    labels = {
        'description': 'Blog Description',
        'tags': 'Subject Tags',
    }

MainProject/apps/URLsub/views.py
#apps/URLsub/views.py
from django.shortcuts import render, redirect
from django.http import  HttpResponseRedirect, HttpResponseNotFound
from .forms import URLSubForm, AdditionalDescriptionForm
from django.contrib.auth.decorators import login_required
from .models import URLsub, Description, Tag
from django.views.generic import DetailView
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage



@login_required
def urlsub(request):
    description_tags = None  # Define description_tags outside of the conditional blocks

    if request.method == 'POST':
        form = URLSubForm(request.POST)
        if form.is_valid():
            url = form.cleaned_data['url']
            user = request.user
            title = form.cleaned_data['title']
            tags = form.cleaned_data['tags']

            existing_submission = URLsub.objects.filter(url=url).first()

            if existing_submission:
                existing_submission.title = title
                existing_submission.tags.set(tags)
                existing_submission.save()
                submission = existing_submission
            else:
                submission = URLsub.objects.create(
                    user=user,
                    url=url,
                    title=title,
                )
                submission.tags.set(tags)

            description_text = form.cleaned_data['description']
            description = Description.objects.create(urlsub=submission, description=description_text, user=user)
            description_tags = description.tags.all()  # Update description_tags here

            description.tags.set(tags)

            return HttpResponseRedirect('thanks_url')

    else:
        form = URLSubForm()

    all_tags = Tag.objects.values_list('name', flat=True).distinct()

    return render(request, 'URLsub/urlsub.html', {'form': form, 'all_tags': all_tags, 'description_tags': description_tags})

@login_required
def url_thanks(request):
    return render(request, 'URLsub/thanks_url.html', {})


##View to see individual blogs and their descriptions, reviews authors etc
class URLsubDetailView(DetailView):
    model = URLsub
    template_name = 'URLsub/urlsub_detail.html'
    context_object_name = 'urlsub'
    paginate_by = 10

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        slug = self.kwargs.get('slug')
        return get_object_or_404(URLsub, pk=pk, slug=slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        additional_descriptions = self.object.additional_descriptions.order_by('timestamp')
        paginator = Paginator(additional_descriptions, self.paginate_by)
        page_number = self.request.GET.get('page')
        additional_descriptions_page = paginator.get_page(page_number)
        context['additional_descriptions_page'] = additional_descriptions_page
        return context


@login_required
def add_additional_description(request, pk, slug):
    urlsub = get_object_or_404(URLsub, pk=pk, slug=slug)
    
    if request.method == 'POST':
        form = AdditionalDescriptionForm(request.POST)
        if form.is_valid():
            additional_description = form.save(commit=False)
            additional_description.urlsub = urlsub
            additional_description.user = request.user
            additional_description.save()

            form.save_m2m()  # Save the tags associated with the additional description

            return redirect('URLsub:urlsub_detail', pk=pk, slug=slug)  # Redirect to the URLsub detail page with slug
    else:
        form = AdditionalDescriptionForm()
    
    return render(request, 'URLsub/add_additional_description.html', {'form': form, 'urlsub': urlsub})

MainProject/templates/URLsub/add_additional_description.html
<!-- add_additional_description.html -->
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Add Additional Description{% endblock title %}

{% block css %}
    {{ block.super }}
    <!-- Add your specific CSS links here for additional description page -->
{% endblock css %}

{% block content %}
<div class="page-container">
    <section class="form-header">
        <h2>Add Additional Description</h2>
        <p>Add an additional description below:</p>
    </section>

    <section class="form-section">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.description.id_for_label }}">Description:</label>
                {{ form.description }}
            </div>
            <div class="form-group">
                <label for="{{ form.tags.id_for_label }}">Tags:</label>
                {{ form.tags }}
            </div>
            <!-- Add other form fields as needed -->

            <button type="submit" class="styled-button">Submit</button>
        </form>
    </section>
</div>
{% endblock content %}

MainProject/templates/URLsub/thanks_url.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block css %} 
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
{% endblock css%}

{% block head_title %}{{ post.title }}{% endblock %}

{% block content %}

  <link rel="stylesheet" type="text/css" href="{% static 'plugins/input-tags/tagsinput.css' %}" />

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="{% static 'plugins/input-tags/tagsinput.js' %}"></script>



<body>
    <p>Thanks for your contribution to The WilderNet!</p>
    

    
    </body>

{% endblock %}

MainProject/templates/URLsub/urlsub.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block css %} 
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
{% endblock css%}

{% block head_title %}{% endblock %}

{% block content %}

  <link rel="stylesheet" type="text/css" href="{% static 'plugins/input-tags/tagsinput.css' %}" />




<div class="page-container">
<header class="header">
  <!-- Insert header content here-->

</header>

  <section class="form-header">
    <h2> Blog Recommendations </h2>
    <p> Help us build our community! Recommend a blog below: </p>
  </section>



      <section class="form-section">
        <form action="{% url 'URLsub:urlsub' %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="{{ form.url.id_for_label }}">Blog URL:</label>
            {{ form.url }}
          </div>
      
          <div class="form-group">
            <label for="{{ form.title.id_for_label }}">Title:</label>
            {{ form.title }}
          </div>
      
     
          <div class="form-group">
            <label for="{{ form.description.id_for_label }}">Add a description:</label>
            {{ form.description }}
          </div>

          <div class="form-group-plugin">
            <label for="{{ form.tags.id_for_label }}">Subject tags:<br>Separate tags by a comma</label>
            {% render_field form.tags class="form-control" id="input-tags" data-role="tagsinput" %}
        </div>
        
        
      

         
          <input type="submit" class="styled-button" value="Submit" name="urlsub">

        </form>
      </section>
      

      
    
</div>
{% endblock content %}

MainProject/templates/URLsub/urlsub_detail.html
<!-- templates/URLsub/urlsub_detail.html -->
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The WilderNet Home</title>
    {% load static %}
    {% block css %}{% endblock css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/URLsub/urlsub_detail.css' %}">
</head>

<body>

    <div class="container-fluid mt-4">
        <div class="row justify-content-center">
                                <!-- Create post and discussion buttons -->
                                <div class="button-container urlsub-detail-buttons">
                                    <a href="{% url 'core:urlsub_post_create' pk=urlsub.pk slug=urlsub.slug %}">
                                        <button class="styled-button">Create Post</button>
                                    </a>

                                    <a href="{% url 'core:url_specific_forum' pk=urlsub.pk slug=urlsub.slug %}">

                                        <button class="styled-button">Discussion</button>
                                    </a>
                                    <a href="{% url 'URLsub:add_additional_description' pk=urlsub.pk slug=urlsub.slug %}">
                                        <button class="styled-button">Add Additional Description</button>
                                    </a>
                                    
                                </div>
            <div class="col-12">
      


             
 <!-- Main URL description -->
<div class="urlsub-card">
    <h1><a href="{{ urlsub.url }}" target="_blank" class="urlsub-title">{{ urlsub.title }}</a></h1>

    <p class = "urlsub-description">{{ urlsub.description }}</p>
    <strong>User: <a href="{% url 'users:profile' urlsub.user.username %}" class="urlsub-username">{{ urlsub.user.username }}</a></strong><br>
    {% for tag in urlsub.tags.all %}
        <a href="{% url 'SubjectTags:blogs_list_by_tag' tag.slug %}" class="badge badge-dark">{{ tag.name }}</a>
        {% if not forloop.last %} {% endif %}
    {% endfor %}
</div>

<!-- Paginated additional descriptions -->
<div class="row">
    {% for description in additional_descriptions_page %}
        <div class="col-12">
            <div class="urlsub-card">
                
                <p class="urlsub-description">{{ description.description }}</p>
                <strong>User: <a href="{% url 'users:profile' description.user.username %}" class="urlsub-username">{{ description.user.username }}</a></strong><br>
                {% for tag in description.tags.all %}
                    <a href="{% url 'SubjectTags:blogs_list_by_tag' tag.slug %}" class="badge badge-dark">{{ tag.name }}</a>
                    {% if not forloop.last %} {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</div>
            </div>
<!-- Pagination links -->
{% if additional_descriptions_page.has_other_pages %}
    <ul class="pagination">
        {% if additional_descriptions_page.has_previous %}
            <li><a href="?page={{ additional_descriptions_page.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in additional_descriptions_page.paginator.page_range %}
            {% if additional_descriptions_page.number == i %}
                <li class="current"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if additional_descriptions_page.has_next %}
            <li><a href="?page={{ additional_descriptions_page.next_page_number }}">&raquo;</a></li>
        {% else %}
            <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
{% endif %}
   
</div>
</body> 

</html>

{% endblock %}