MainProject/apps/StripePayment/urls.py
#apps/StripePayment/urls.py
from django.contrib import admin
from django.urls import path
from StripePayment.views import (
    DonationView,
    DonationSuccessView,
    DonationCancelView,
    SubscriptionView,
    SubscriptionSuccessView,
    SubscriptionCancelView,
    CreateSubscriptionCheckoutSessionView,
    CombinedView,
    SubscriptionListView,
  #  CancelSubscriptionView,
   # SubscriptionCancelledView,
  #  ManageSubscriptionView,
    error_view,
    webhook_subscription,
)

app_name = 'StripePayment'  # Namespace for the app's URLs


urlpatterns = [
    path('admin/', admin.site.urls),

    path('donation/', DonationView.as_view(), name='donation-view'),  # Map the DonationView to a URL

    path('donation-cancel/', DonationCancelView.as_view(), name='donation-cancel'),
    path('donation-success/', DonationSuccessView.as_view(), name='donation-success'),

    path('subscription/', SubscriptionView.as_view(), name='subscription-view'),
    path('create-subscription-session/', CreateSubscriptionCheckoutSessionView.as_view(), name='create-subscription-session'),
 
    path('subscription-success/', SubscriptionSuccessView.as_view(), name='subscription_success'),
    path('subscription-cancel/', SubscriptionCancelView.as_view(), name='subscription_cancel'),

    path('subscription_list/', SubscriptionListView.as_view(), name='subscription_list'),

    path('donate/',  CombinedView.as_view(), name='combined-donation'),
    path('unsubscribe/<int:subscription_id>/', SubscriptionView.as_view(), name='unsubscribe_subscription'),

 #   path('cancel-subscription/', CancelSubscriptionView.as_view(), name='cancel_subscription'),
  #  path('subscription-cancelled/', SubscriptionCancelledView.as_view(), name='subscription_cancelled'),
   # path('manage-subscription/', ManageSubscriptionView.as_view(), name='manage_subscription'),
    path('error/', error_view, name='error'),

    path('webhook-subscription/', webhook_subscription, name='stripe_webhook_subscription'), 
]

MainProject/apps/users/urls.py
# users/urls.py        
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView
)

from .views import signup, log_in, log_out, profile, edit_profile
from django.urls import reverse_lazy
from . import views


urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    

    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        success_url='/users/password_reset/done/'),
        name='password_reset'
    ),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url='/users/reset/done/'),
        name='password_reset_confirm'
    ),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),

    path('profile/<str:username>/', profile, name='profile'),

    path('edit-profile/<str:username>/', edit_profile, name='edit_profile'),  # Include 'username' parameter

    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done')),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),



]

MainProject/blog/urls.py
# blog/urls.py

"""blog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve





urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('apps.core.urls', 'core'), namespace='core')),    
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),  
    path('', include(('apps.ContactUs.urls', 'ContactUs'), namespace='ContactUs')),
    path('', include(('apps.URLsub.urls', 'URLsub'), namespace='URLsub')),  
    path('', include(('apps.Search.urls', 'Search'), namespace='Search')),
    path('', include(('SubjectTags.urls', 'SubjectTags'), namespace='SubjectTags')),
    path('', include(('StripePayment.urls', 'StripePayment'), namespace='StripePayment')),
    path('legal/', include('apps.legal.urls')),  # Include legal app URLs




]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
]

MainProject/apps/StripePayment/views.py
#apps/StripePayment/views.py
import stripe
from .models import Price, Product, Donation, Subscription
from django.conf import settings
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.views import View
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.core.mail import send_mail
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from apps.users.models import User
from stripe.error import StripeError
from StripePayment.utils import get_or_create_stripe_customer_id, create_stripe_checkout_session
from decimal import Decimal
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST
import logging
import json

 
stripe.api_key = settings.STRIPE_SECRET_KEY
logger = logging.getLogger(__name__)


class DonationView(View):
    template_name = "StripePayment/donation.html"

    def get(self, request, *args, **kwargs):
        # Logic to render the donation form
        return render(request, self.template_name, context={})

    def post(self, request, *args, **kwargs):
        # Logic to process the donation payment
        try:
            amount = int(request.POST.get('amount'))  # Assuming a form field for donation amount
            domain = "https://thewildernet.com"  # Default to thewildernet.com

            # Redirect www version to non-www if accessing through www
            if 'www.' in request.META.get('HTTP_HOST'):
                return redirect("https://thewildernet.com" + request.get_full_path(), permanent=True)

            # Adjust domain if in debug mode
            if settings.DEBUG:
                domain = "http://127.0.0.1:8000"  # Replace with your debug domain
                
            checkout_session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                line_items=[
                    {
                        'price_data': {
                            'currency': 'usd',
                            'unit_amount': amount * 100,  # Stripe uses amount in cents
                            'product_data': {
                                'name': 'Donation',  # Change as needed
                            },
                        },
                        'quantity': 1,
                    },
                ],
                mode='payment',
                success_url=domain + '/donation-success/',
                cancel_url=domain + '/donation-cancel/',
            )

            # Check if the user is authenticated before associating with the donation
            user = request.user if request.user.is_authenticated else None
                 
                # Create and save a Donation instance
            donation = Donation(
                amount=amount,
                stripe_checkout_session_id=checkout_session.id,
                user=user,  # Add the logged-in user to the donation
             #   stripe_customer_id=user.stripe_customer_id if user else None,

            )
            donation.save()

            return HttpResponseRedirect(checkout_session.url)
        except Exception as e:
            # Handle the exception appropriately (e.g., show an error message)
            return render(request, self.template_name, context={'error_message': str(e)})

    def get_donation_info(self):
        return {}  



class DonationSuccessView(TemplateView):
    template_name = "StripePayment/donation_success.html"
 
class DonationCancelView(TemplateView):
    template_name = "StripePayment/donation_cancel.html"


#This view handles the subscriptions
class SubscriptionView(View):
    template_name = "StripePayment/subscription.html"

    def get_subscription_info(self, request, *args, **kwargs):
        try:
            subscription_info = []

            prices = stripe.Price.list(active=True, limit=10).data  # Retrieve subscription prices

            for price in prices:
                if price.type == 'recurring':
                    product = stripe.Product.retrieve(price.product)
 
                    if hasattr(product, 'name'):
                        price_amount = float(price.unit_amount_decimal) / 100  # Convert to integer and then divide by 100

                        subscription_info.append({
                            'id': price.id,  # Include the price ID
                            'product_name': product.name,
                            'price': "{:.2f}".format(price_amount),
                            'is_active': False,
                        })

            return subscription_info

        except stripe.error.StripeError as e:
        # Handle Stripe API errors
            messages.error(request, f'Stripe Error: {str(e)}')
            return []    

    def get_user_subscription_name(self, user):
    # Replace this with your logic to get the name of the user's subscription
        user_subscription = Subscription.objects.filter(user=user, is_active=True).first()
        return user_subscription.product if user_subscription else None

    def is_user_subscribed(self, user):
    # Replace this with your logic to check if the user is subscribed
        return Subscription.objects.filter(user=user, is_active=True).exists()


    def create_new_subscription(self, request):
        # Create a new instance of Subscription here
        return Subscription.objects.create(
            user=request.user,
            subscription_plan_id='default_plan',  # Set the default plan ID or use logic to determine it
            status='pending'
        )


    def get(self, request, *args, **kwargs):
       
        existing_stripe_customer_id = get_or_create_stripe_customer_id(request.user, create=True)
        subscription_info = self.get_subscription_info(request)
        user_subscribed = self.is_user_subscribed(request.user)
        user_subscription_name = self.get_user_subscription_name(request.user)


        context = {
            'subscription_info': subscription_info,
            'user_subscribed': user_subscribed,
            'user_subscription_name': user_subscription_name,
            'stripe_customer_id': existing_stripe_customer_id,
        }
        print(context)
        return render(request, self.template_name, context)


    def post(self, request, *args, **kwargs):
        stripe.api_key = settings.STRIPE_SECRET_KEY  # Set the Stripe secret key

        try:
            plan_id = request.POST.get('plan_id')  # Assuming a form field for subscription plan selection
            existing_subscription = Subscription.objects.filter(user=request.user, is_active=True).first()

            if existing_subscription:
            # User already has an active subscription, handle accordingly
                messages.warning(request, 'You are already subscribed to a plan.')
                return redirect('subscription_list')  # Change to your actual subscription list URL

        # Call the handle_subscription_selection method
            return self.handle_subscription_selection(request, plan_id)

        except stripe.error.StripeError as e:
        # Handle Stripe errors
            return render(request, self.template_name, {'error': str(e)})
        except ValueError as e:
        # Handle invalid plan ID error
            return render(request, self.template_name, {'error': str(e)})




class CreateSubscriptionCheckoutSessionView(View):
    @csrf_exempt
    def post(self, request, *args, **kwargs):
        plan_id = request.POST.get('plan_id')  # Assuming the plan_id is sent from the form
        user = request.user
        existing_subscription = Subscription.objects.filter(user=user, is_active=True).first()

        if existing_subscription:
            # If the user already has an active subscription, check if they are changing the plan
            if existing_subscription.subscription_plan_id == plan_id:
                messages.warning(request, 'You are already subscribed to this plan.')
                return redirect('subscription_list')
            else:
                # Cancel the existing subscription
                self.unsubscribe(request, existing_subscription.id)

        domain = "https://thewildernet.com"  # Default to thewildernet.com

        # Redirect www version to non-www if accessing through www
        if 'www.' in request.META.get('HTTP_HOST'):
            return redirect("https://thewildernet.com" + request.get_full_path(), permanent=True)

        # Adjust domain if in debug mode
        if settings.DEBUG:
            domain = "http://127.0.0.1:8000"  # Replace with your debug domain

        price = stripe.Price.retrieve(plan_id)
      #  subscription_amount = float(price.unit_amount_decimal) / 100  # Convert to integer and then divide by 100

        product = stripe.Product.retrieve(price.product)
       # product_name = product.name if hasattr(product, 'name') else "Unknown Product"


        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[
                {
                    'price': plan_id,
                    'quantity': 1,
                },
            ],
            mode='subscription',
            success_url=domain + '/subscription-success/',
            cancel_url=domain + '/subscription-cancel/',
        )


        return redirect(checkout_session.url)
    
    def unsubscribe(self, request, subscription_id):
        # Implement your logic to cancel the subscription
        pass

class SubscriptionSuccessView(TemplateView):
    template_name = "StripePayment/subscription_success.html"
 
class SubscriptionCancelView(TemplateView):
    template_name = "StripePayment/subscription_cancel.html"

class CombinedView(View):
    template_name = "StripePayment/donate.html"

    def fetch_donation_info(self):

MainProject/templates/StripePayment/cancel.html
<!--templates/StripePaymemt/cancel.html-->

<html>
 
<head>
    <title>Checkout canceled</title>
</head>
 
<body>
    <section>
<p>Checkout canceled</p>    </section>
</body>
 
</html>

MainProject/templates/StripePayment/combined.html
<!-- apps/StripePayment/templates/StripePayment/combined.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Combined Page</title>
</head>
<body>

    <!-- Donation Section -->
    <div>
        <h2>Donation Section</h2>

        {% for donation in donation_info %}
            <p>Donation ID: {{ donation.id }}, Amount: {{ donation.amount }}, Type: {{ donation.type }}</p>
        {% endfor %}
    </div>

    <!-- Subscription Section -->
    <div>
        <h2>Subscription Section</h2>
        {% if user_has_active_subscription %}
            <!-- Display information about the user's current subscription -->
            <p>You are currently subscribed to the {{ user_subscription_name }} plan.</p>
            <p>Price: ${{ user_subscription_price }}</p>
            <!-- Additional details about the subscription -->
        {% else %}
            <!-- Display subscription options for users without an active subscription -->
            <label for="subscriptionOptions">Choose a subscription:</label>
            <select id="subscriptionOptions">
                <option value="price_1OdPwPAKSIZ6blYwGuqwrjKa">Premium Subscription - $5.00 USD</option>
                <option value="price_another_id">Another Subscription - $X.XX USD</option>
                <!-- Add other subscription options as needed -->
            </select>
            <button onclick="subscribe()">Subscribe</button>
        {% endif %}
    </div>

</body>
</html>

MainProject/templates/StripePayment/donate.html
{% extends 'base.html' %}

{% block donate_button %}
    {# This block is intentionally left empty to remove the donate button on the donate page #}
{% endblock donate_button %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Donation and Subscription Page</title>
    {% load static %}
    {% block css %}{% endblock css %}
        
    <link rel="stylesheet" type="text/css" href="{% static 'css/StripePayment/donate.css' %}">
    
</head>

<body class="donate-page">



    <!-- Donation and Subscription Sections Container -->
    <div class="donation-container custom-wrapper">

        <!-- Donation Form Section -->
        <div class="section-container donate-section-container custom-post-grid">
            <h2>Make a Donation</h2>
            <form action="{% url 'StripePayment:donation-view' %}" method="POST" id="donation-form">
                {% csrf_token %}
                <label for="amount">Amount (in dollars):</label>
                <input type="text" id="amount" name="amount" required>
                <button type="submit">Donate</button>
            </form>
        </div>

        <!-- Subscription Form Section -->
       <!-- <div class="section-container donate-section-container custom-post-grid">
            {% if user.is_authenticated %}
                {% if user_subscribed %}-->
                    <!-- Content for users who are subscribed -->
                  <!--  <h2>Manage Your Subscription</h2>
                    <p>You are currently subscribed to: {{ user_subscription.product_name }} - ${{ user_subscription.price }} USD per month.</p>
                    <p>
                        <a href="{% url 'StripePayment:manage_subscription' %}">Manage Subscription</a> |
                        <a href="{% url 'StripePayment:subscription_list' %}">View Subscription Details</a>
                    </p>
                {% else %}-->
                    <!-- Content for users who are not subscribed -->
                <!--  <h2>Subscribe Now</h2>
                    <form action="{% url 'StripePayment:create-subscription-session' %}" method="POST">
                        {% csrf_token %}
                        {% for subscription in subscription_info %}
                            <label>
                                <input type="radio" name="plan_id" value="{{ subscription.id }}" required>
                                {{ subscription.product_name }} - ${{ subscription.price|floatformat:2 }} USD/month
                            </label>
                            <br>
                        {% endfor %}
                        <button type="submit">Subscribe</button>
                    </form>
                {% endif %}
            {% else %}-->
                <!-- Content for users who are not logged in -->
              <!--  <p>Please <a href="{% url 'users:login' %}">log in</a> to see subscription options.</p>
            {% endif %}-->
        </div>
    </div>

</body>

</html>
{% endblock %}

MainProject/templates/StripePayment/donation.html
<!-- templates/StripePayment/donation.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Donate</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
</head>
<body>
    <section>
        <div class="donation-form">
            <h2>Make a Donation</h2>
            <form action="" method="POST" id="donation-form">
                {% csrf_token %}
                <label for="amount">Amount (in dollars):</label>
                <input type="text" id="amount" name="amount" required>
                <button type="submit">Donate</button>
            </form>
        </div>
    </section>
</body>
</html>

MainProject/templates/StripePayment/donation_success.html
<!--templates/StripePaymemt/success.html-->

<html>
 
<head>
    <title>Thanks for your order!</title>
</head>
 
<body>
    <section>
        <p>
            Thank you for your donation!
            <a href="mailto:contact.jidder@gmail.com">contact.jidder@gmail.com</a>.
        </p>

    </section>
</body>
 
</html>

MainProject/templates/StripePayment/error.html
<!-- templates/error.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <h1>Oops! An error occurred.</h1>
    <p>{{ error_message }}</p>
    <p><a href="{% url 'core:home' %}">Go back to home</a></p>
</body>
</html>

MainProject/templates/StripePayment/landing.html
<!--templates/StripePaymemt/landing.html-->
<!DOCTYPE html>
<html>
 
<head>
    <title>Donate to Jidder!</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
</head>
 
<body>
    <section>
        <div class="product">
            <div class="description">
                <h3>{{ product.name }}</h3>
                <hr />
                {% for price in prices %}
 
                <div>
                    <h5>${{ price.get_display_price }}</h5>
                    <form action="{% url 'StripePayment:create-checkout-session' price.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit">Checkout</button>
                    </form>
                </div>
 
                {% endfor %}
            </div>
        </div>
    </section>
</body>
 
</html>

MainProject/templates/StripePayment/manage_subscription.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage Subscription</title>
</head>
<body>
    <h1>Manage Your Subscription</h1>
    <p>Click the button below to manage your subscription:</p>
    <form action="{% url 'manage-subscription' %}" method="GET">
        <button type="submit">Manage Subscription</button>
    </form>
</body>
</html>

MainProject/templates/StripePayment/subscription.html
<!DOCTYPE html>
<html>
<head>
    <title>Subscribe</title>
</head>
<body>
    <section>
        <div class="subscription-form">
            <h2>Subscribe Now</h2>
            <form action="/create-subscription-session/" method="POST">
                {% csrf_token %}
                {% for subscription in subscription_info %}
                <label>
                    <input type="radio" name="plan_id" value="{{ subscription.id }}" required>
                    {{ subscription.name }} - $ {{ subscription.price }} USD
                </label>
                    <br>
                {% endfor %}
                <button type="submit">Subscribe</button>
            </form>

        </div>
    </section>
</body>
</html>

MainProject/templates/StripePayment/subscription_cancel.html
<!-- apps/StripePayment/templates/StripePayment/subscription_cancelled.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Subscription Cancelled</title>
</head>
<body>
    <h2>Your subscription has been cancelled.</h2>
    <p>
        <a href="{% url 'StripePayment:combined-donation' %}">Go back to Donate</a>
    </p>
</body>
</html>

MainProject/templates/StripePayment/subscription_cancelled.html
<!-- apps/StripePayment/templates/StripePayment/subscription_cancelled.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Subscription Canceled</title>
    <style>
        /* Add your styles here if needed */
    </style>
</head>
<body>
    <h2>Your subscription has been canceled</h2>
    <!-- Add any additional content or styling as needed -->
</body>
</html>

MainProject/templates/StripePayment/subscription_list.html
<!-- subscription_list.html -->
<h1>You are currently subscribed to:</h1>
{% for subscription in subscriptions %}
    <p>{{ subscription.product }} - ${{ subscription.amount }}/month</p>
    {% if subscription.is_active %}
        <a href="{% url 'StripePayment:unsubscribe_subscription' subscription.id %}">Unsubscribe</a>
    {% else %}
        <p>Unsubscribed</p>
    {% endif %}
{% endfor %}

MainProject/templates/StripePayment/subscription_success.html
<!--templates/StripePaymemt/subscription_success.html-->

<html>
 
<head>
    <title>Thanks for your order!</title>
</head>
 
<body>
    <section>
        <p>
            Thank you for subscribing!
            <a href="mailto:contact.jidder@gmail.com">contact.jidder@gmail.com</a>.
        </p>

    </section>
</body>
 
</html>

MainProject/templates/StripePayment/success.html
<!--templates/StripePaymemt/success.html-->

<html>
 
<head>
    <title>Thanks for your order!</title>
</head>
 
<body>
    <section>
        <p>
            We appreciate your business! If you have any questions, please email
            <a href="mailto:orders@example.com">orders@example.com</a>.
        </p>

    </section>
</body>
 
</html>