MainProject/apps/Search/urls.py
from django.urls import path
from . import views

app_name = 'Search'

urlpatterns = [
    # Other URL patterns
    path('search/', views.search_view, name='search_view'),
    path('elastic-search/', views.elastic_search_view, name='elastic_search_view'),
    path('elastic-search/history/', views.view_search_history, name='search_history'),


]

MainProject/apps/URLsub/urls.py
#URLsub/urls.py
from django.urls import path
from . import views
from .views import URLsubDetailView, add_additional_description

app_name = 'URLsub'  # Add the app namespace


urlpatterns = [
    path('urlsub/', views.urlsub, name='urlsub'),
    path('urlsub/thanks_url', views.url_thanks, name='thanks_url'),
    path('urlsub/<int:pk>/<slug:slug>/', URLsubDetailView.as_view(), name='urlsub_detail'),
    path('urlsub/<int:pk>/<slug:slug>/add_additional_description/', add_additional_description, name='add_additional_description'),

]

MainProject/apps/core/urls.py
# core/urls.py
from django.urls import path
from . import views
from .views import  HomeView, PostView, PostCreateView, PostUpdateView, PostDeleteView,  ForumView, URLSpecificPostCreateView, URLSpecificPostView, URLSpecificForumView, YourPostsView, SavedForLaterView, LikedView
#, AddDislike, AddLike, 

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('Forum', ForumView.as_view(), name='forum'),
    path('post/<int:pk>/<slug:slug>/', PostView.as_view(), name='post'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),

    path('post/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),

    path('About/', views.AboutView, name='about'),
    path('Trending/', views.TrendingView, name='trending'),
    path('Recommendations/', views.RecommendationsView, name='recommendations'),
    path('Subscriptions/', views.SubscriptionsView, name='subscriptions'),

    path('YourPosts/', views.YourPostsView, name='yourposts'),

    path('SavedForLater/', views.SavedForLaterView, name='savedforlater'),
    path('Liked/', views.LikedView, name='liked'),

    path('urlsub/<int:pk>/<slug:slug>/create_post', URLSpecificPostCreateView.as_view(), name='urlsub_post_create'),
    path('urlsub/<int:pk>/<slug:slug>/<int:post_pk>/<slug:post_slug>/', URLSpecificPostView.as_view(), name='url_specific_post'),
    path('urlsub/<int:pk>/<slug:slug>/discussion/', URLSpecificForumView.as_view(), name='url_specific_forum'),

 #   path('rsstest/', RSSPageView.as_view(), name="rsstest"),

]

MainProject/apps/users/urls.py
# users/urls.py        
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView
)

from .views import signup, log_in, log_out, profile, edit_profile
from django.urls import reverse_lazy
from . import views


urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    

    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        success_url='/users/password_reset/done/'),
        name='password_reset'
    ),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url='/users/reset/done/'),
        name='password_reset_confirm'
    ),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),

    path('profile/<str:username>/', profile, name='profile'),

    path('edit-profile/<str:username>/', edit_profile, name='edit_profile'),  # Include 'username' parameter

    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done')),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),



]

MainProject/blog/urls.py
# blog/urls.py

"""blog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve





urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('apps.core.urls', 'core'), namespace='core')),    
    path('users/', include(('apps.users.urls', 'users'), namespace='users')),  
    path('', include(('apps.ContactUs.urls', 'ContactUs'), namespace='ContactUs')),
    path('', include(('apps.URLsub.urls', 'URLsub'), namespace='URLsub')),  
    path('', include(('apps.Search.urls', 'Search'), namespace='Search')),
    path('', include(('SubjectTags.urls', 'SubjectTags'), namespace='SubjectTags')),
    path('', include(('StripePayment.urls', 'StripePayment'), namespace='StripePayment')),
    path('legal/', include('apps.legal.urls')),  # Include legal app URLs




]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
]

MainProject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

  <!-- Bootstrap and CSS files -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" type= "text/css" href="/static/css/index_20240305.css" />

  <!--Font-->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="{% static 'plugins/input-tags/tagsinput.js' %}"></script>
  
  <script>
      $("input[name='tags']").tagsinput({
         confirmKeys:[13] //-- Only enter                                                                                   
       });
    </script>


<title>The WilderNet Beta</title>

  <style>
    {% block css %}
    {% endblock css %}
  </style>
</head>

<body>


  <header class="header">
    <div class="logo left">
   <!-- <i id="menu" class="material-icons">menu</i>-->
    <a class="logo" href="{% url 'core:home' %}"><span>
    <img id="logo" src="{% static '/img/cat.png' %}" width="60" height="60"></span></a>
    <a href="{% url 'core:home' %}"
    class="site-title {% if request.path == '/' %}active{% endif %}">The WilderNet </a>
    </div>

   
   
    
    <div class="container">


      <div class="search center">
        <form method="get" action="{% url 'Search:search_view' %}">
          {{ form.search.as_p }}
          <input type="text" placeholder="Search" name="query">
          <button><i class="material-icons">search</i></button>
        </form>
        
    
         
        <div class="dropdown">
          <div class="icons right">
            {% if user.is_authenticated %}
              {% if user.profile.avatar %}
                <div class="avatar-icon-dropdown-container">
                  <div class="avatar-icon" style="background-image: url('{{ user.profile.avatar.url }}');"></div>
                </div>
           
                  {% else %}
                      <i class="material-icons">account_circle</i>
                  {% endif %}
                  {% else %}
            <!-- Placeholder for non-authenticated users -->
            <i class="material-icons">account_circle</i>
            {% endif %}
          </div>
              <div class="dropdown-content">
                  {% if user.is_authenticated %}
                      <a href="{% url 'users:profile' user.username %}">Hi {{ user.username }}!</a>
                      <hr>
                      <a href="{% url 'core:post_create' %}"
                          class="{% if request.path == '/post/create/' %}active{% endif %}">Create a Post</a><br>
      
                      <a href="#">Settings</a><br>
                      <a href="#">Dark Mode</a><br>
                      <a href="#">Location</a><br>
      
                      <p><a href="{% url 'users:logout' %}">Log Out</a></p>
                  {% else %}
                      <a href="{% url 'users:login' %}">Log In</a><br>
                      <a href="{% url 'users:signup' %}">Sign up</a>
                  {% endif %}
              </div>
          </div>

       <!--sign up login button-->
       {% block login_button %}
       {% if not user.is_authenticated %}
       <div class="login-button">
         <a href="{% url 'users:login' %}">
           <button>Login</button>
         </a>
       </div>
        {% endif %}
        {% endblock login_button %}

          {% block donate_button %}
          <div class="donation-button">
            <a href="{% url 'StripePayment:combined-donation' %}">
              <button>Donate Now!</button>
            </a>
          </div>
      </div>
      {% endblock donate_button %}

   

</header>         
  
  
</div>
</nav>
 


<main>
  <div class="side-bar">
    <!-- <div class=”side-bar”> -->
    <div class="nav">

     <span>
          <a href="{% url 'core:home' %}"
          class="nav-item nav-link  {% if request.path == '/' %}active{% endif %}">
         <i class="material-icons">home</i> Home </span></a>             
 
<!-- Someday I will have enough data to implement the below elements. For now it is commented out:
       <a class="nav-link" href="/Trending" {% block Trendingactive %}{% endblock Trendingactive %} >
        <i class="material-icons">local_fire_department</i>
        <span>Trending</span>
     </a>

     {% if user.is_authenticated %}
      <a class="nav-link" href="/Recommendations" {% block Recommendationsactive %}{% endblock Recommendationsactive %} > 
      <span>
          <i class="material-icons">done</i> Recommendations </span>
      </a>


      <a class="nav-link" href="/Subscriptions"{% block Subscriptionsactive %}{% endblock Subscriptionsactive %} > 
      <span>
          <i class="material-icons">subscriptions</i> Subscriptions </span>
      </a> 
      {% endif %}-->
      <hr>

      {% if user.is_authenticated %}
      <span>
        <a  href="{% url 'URLsub:urlsub' %}"
          class="nav-item nav-link  {% if request.path == '/' %}active{% endif %}">
          <i class="material-icons">dataset</i> Add a Blog </span></a>
      


      <span>
        <a  href="{% url 'ContactUs:contact' %}"
          class="nav-item nav-link  {% if request.path == '/' %}active{% endif %}">
          <i class="material-icons">contact_page</i> Contact Us </span></a>
    <hr>
         
    {% endif %}
     
        <span>  <a href="{% url 'core:forum' %}"
          class="nav-item nav-link  {% if request.path == '/' %}active{% endif %}">
            <i class="material-icons">subscriptions</i> Forum </span></a>
   
            {% if user.is_authenticated %}
            <span><a href="{% url 'core:post_create' %}"
              class="nav-item nav-link  {% if request.path == '/' %}active{% endif %}">
              <i class="material-icons">post_add</i>Create a Post</span></a>
            {% endif %}
        <a class="nav-link" href="/YourPosts" {% block YourPostsactive %}{% endblock YourPostsactive %}> 
          <span>
              <i class="material-icons">local_post_office</i> Your Posts </span>
          </a>
    
  
        <hr>

      


   
      <a class="nav-link" href="/About" > 
      <span>
          <i class="material-icons">library_add_check</i> About </span>
      </a>


      {% if user.is_authenticated %}
      <a class="nav-link" href="{% url 'Search:search_history' %}">
        <span>
          <i class="material-icons">history</i> History
        </span>
      </a>
   

      



      <a class="nav-link" href="/SavedForLater" {% block SavedForLateractive %}{% endblock SavedForLateractive %}> 
      <span>
          <i class="material-icons">watch_later</i> Saved for Later </span>
      </a>



      <a class="nav-link" href="/Liked" {% block Likedactive %}{% endblock Likedactive %} > 
      <span>
          <i class="material-icons">thumb_up</i> Liked </span>
      </a>
      {% endif %}
    </div>

      
    </div>





  {% block content %}
  {% endblock content %}

</body>
</html>